apps:
  - script: 'serve'
    name: 'landing-ever'
    watch: true
    env:
      PM2_SERVE_PATH: '.'
      PM2_SERVE_PORT: 8076
      PM2_SERVE_SPA: 'true'
      PM2_SERVE_HOMEPAGE: '/index.html'
      # PM2_SERVE_BASIC_AUTH: 'true'
      # PM2_SERVE_BASIC_AUTH_USERNAME: ${}
      # PM2_SERVE_BASIC_AUTH_PASSWORD: ${}
